
include("types.jl")
include("utils.jl")
include("optim_utils.jl")
include("domain.jl")
include("models/include.jl")
include("acquisition_function/include.jl")
include("acquisition_maximizer/include.jl")
include("model_fitter/include.jl")
include("term_cond.jl")
include("plot.jl")
include("bo.jl")
